openapi: "3.0.1"
info:
  title: "${ProjectName}-${ProjectEnvironment}-backend-api"
  version: "1.0"
paths:
  /sandbox:
    post:
      responses:
        "400":
          description: "400 response"
          content: {}
        "200":
          description: "200 response"
          content: {}
      # 'x-amazon-apigateway-integration' 설명:
      #  - https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html
      x-amazon-apigateway-integration:
#        credentials:
#          Fn::GetAtt: [BackendApiRole, Arn]
        httpMethod: "POST"
        uri:
#          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:states:action/StartSyncExecution
          # https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-custom-integrations.html
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MainFunction.Arn}/invocations
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_templates"
        type: "aws_proxy"
components: {}
